<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Get Api suites" duration-ms="9087" started-at="2021-09-24T08:27:33Z" finished-at="2021-09-24T08:27:43Z">
    <groups>
    </groups>
    <test name="signup_suite" duration-ms="596" started-at="2021-09-24T08:27:33Z" finished-at="2021-09-24T08:27:34Z">
    </test> <!-- signup_suite -->
    <test name="login_suite" duration-ms="9087" started-at="2021-09-24T08:27:33Z" finished-at="2021-09-24T08:27:43Z">
      <class name="testcases.LoginTest">
        <test-method status="PASS" signature="setUp(org.testng.ITestContext)[pri:0, instance:testcases.LoginTest@6aaa5eb0]" name="setUp" is-config="true" duration-ms="6327" started-at="2021-09-24T13:57:34Z" finished-at="2021-09-24T13:57:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@548e6d58]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp(org.testng.ITestContext)[pri:0, instance:testcases.LoginTest@6aaa5eb0]" name="setUp" is-config="true" duration-ms="6045" started-at="2021-09-24T13:57:34Z" finished-at="2021-09-24T13:57:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@548e6d58]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="login1()[pri:0, instance:testcases.LoginTest@6aaa5eb0]" name="login1" duration-ms="52" started-at="2021-09-24T13:57:40Z" description="Verify login functionality" finished-at="2021-09-24T13:57:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testcases.LoginTest.login1(LoginTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login1 -->
        <test-method status="PASS" signature="login2()[pri:0, instance:testcases.LoginTest@6aaa5eb0]" name="login2" duration-ms="21" started-at="2021-09-24T13:57:40Z" description="Verify signup functionality" finished-at="2021-09-24T13:57:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login2 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:testcases.LoginTest@6aaa5eb0]" name="tearDown" is-config="true" duration-ms="2105" started-at="2021-09-24T13:57:40Z" finished-at="2021-09-24T13:57:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login2 status=SUCCESS method=LoginTest.login2()[pri:0, instance:testcases.LoginTest@6aaa5eb0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:testcases.LoginTest@6aaa5eb0]" name="tearDown" is-config="true" duration-ms="2101" started-at="2021-09-24T13:57:40Z" finished-at="2021-09-24T13:57:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login1 status=FAILURE method=LoginTest.login1()[pri:0, instance:testcases.LoginTest@6aaa5eb0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- login_suite -->
  </suite> <!-- Get Api suites -->
</testng-results>
